### ISSUE TITLE
Document the pattern option

### ISSUE THREAD

**Issue by alexkurtz** [chadly/metalsmith-flatten#1]
Basically, I cannot understand the include/exclude semantics for the pattern option. If adding the "*_/_" option, all the folders get flattened, regardless of any other option.

**Comment by chadly** [comment]
It uses [multimatch](https://github.com/sindresorhus/multimatch) under the covers for matching patterns.

Does the last example not work for you?

``` js
var metalsmith = new Metalsmith(__dirname)
  .use(flatten({
    pattern: [
        "**/*",
        "!my-other-dir"
    ]
  }));
```

That will flatten everything except anything in `my-other-dir`.
